name: dirtyhash
version: 0.0.1
description: Passing hash from Dart to JS via js-interop.
dependencies:
  js: ^0.6.0
transformers:
- $dart2js:
    checked: false
    minify: false
    sourceMaps: true
    suppressWarnings: false
    suppressHints: false
    csp: false
    commandLineOptions:
    - --trust-primitives
#    - --disable-type-inference
#    - --trust-type-annotations
#    - --conditional-directives
#    - --enable-experimental-mirrors
#    - --suppress-warnings
#    - --suppress-hints
